In [5]:
from __future__ import print_function

from keras.models import Model
from keras.layers import Input, LSTM, Dense
import numpy as np
import io

batch_size = 100  # Batch size for training.
epochs = 200
latent_dim = 512  # Latent dimensionality of the encoding space.
num_samples = 6000 # Number of samples to train on.

In [6]:
data_path = 'data/f8k_train_caps'

In [7]:
img_mat_old=np.load('data/f8k_train_ims.npy')  
   

In [8]:
with io.open(data_path, 'r', encoding='utf-8') as f:
    lines_old = f.read().split('\n')
    
img_mat=img_mat_old[::5]
lines=lines_old[::5]
img_mat = 10*img_mat


In [9]:
input_words = set()
target_words = set()
input_texts = []
target_texts = []
k=0
for line in lines[: min(num_samples, len(lines) - 1)]:
    input_text = line
    target_text = line
    print(input_text)
    print(target_text)
    print(img_mat[k])
    target_text = 'STR ' + target_text + ' END'
    inp=input_text.split(' ')
    tar=target_text.split(' ')

    input_texts.append(inp)
    target_texts.append(tar)
    for wrd in inp:
            input_words.add(wrd)
    for wrd in tar:
            target_words.add(wrd)
    k=k+1
            
print(input_words)
print(target_words)
print(input_texts)
print(target_texts)
input_words.add('STR')
input_words.add('END')

A black dog is running after a white dog in the snow .
A black dog is running after a white dog in the snow .
[0.14008796 0.         0.         ... 0.         0.         0.        ]
A little baby plays croquet .
A little baby plays croquet .
[0.         0.         0.00057003 ... 0.         0.         0.28307652]
A brown dog in the snow has something hot pink in its mouth .
A brown dog in the snow has something hot pink in its mouth .
[0.10230295 0.         0.         ... 0.         0.         0.        ]
A brown dog is running along a beach .
A brown dog is running along a beach .
[0.        0.        0.        ... 0.        0.2273979 0.       ]
A black and white dog with a red Frisbee standing on a sandy beach .
A black and white dog with a red Frisbee standing on a sandy beach .
[0.         0.         0.         ... 0.03796998 0.         0.        ]
A cyclist wearing a red helmet is riding on the pavement .
A cyclist wearing a red helmet is riding on the pavement .
[0.         0.    

A brown dog chasing a yellow toy .
A brown dog chasing a yellow toy .
[0.         0.         0.         ... 0.         0.23988687 0.        ]
A brown dog carrying a black object .
A brown dog carrying a black object .
[0.00091862 0.         0.08254684 ... 0.         0.12562719 0.        ]
A man attached to strings is watched by a crowd .
A man attached to strings is watched by a crowd .
[0.         0.03653735 0.28835124 ... 0.         0.         0.        ]
A little boy kicks a soccer ball in the park .
A little boy kicks a soccer ball in the park .
[0.         0.         0.         ... 0.         0.24180484 0.12087125]
A girl and boy bounce on large balls .
A girl and boy bounce on large balls .
[0.         0.         0.00223043 ... 0.         0.52204245 0.        ]
A kid in red falls as he struggles with a kid in white to get to a soccer ball .
A kid in red falls as he struggles with a kid in white to get to a soccer ball .
[0.         0.         0.         ... 0.         0.24191603 

A black and white dog is catching a red and green object in his mouth .
A black and white dog is catching a red and green object in his mouth .
[0.         0.         0.3701252  ... 0.         0.25927177 0.        ]
A dog and two people .
A dog and two people .
[0.        0.        0.        ... 0.        0.4528235 0.       ]
A white ad brown dog is running on grass
A white ad brown dog is running on grass
[0.         0.         0.25087723 ... 0.         0.4966439  0.        ]
Snowboarders are jumping their boards off a mound of snow .
Snowboarders are jumping their boards off a mound of snow .
[0.06914863 0.         0.         ... 0.         0.00225905 0.0167326 ]
A cheerleader dressed in red smiles and cheers .
A cheerleader dressed in red smiles and cheers .
[0.         0.         0.         ... 0.         0.         0.04981927]
A baseball player swings at a baseball .
A baseball player swings at a baseball .
[0. 0. 0. ... 0. 0. 0.]
A group of football players are playing football .

A child leaping from bed to bed behind the back of a man .
A child leaping from bed to bed behind the back of a man .
[0. 0. 0. ... 0. 0. 0.]
Two girls in blue and teal dresses and large hats are standing next to a large tree trunk .
Two girls in blue and teal dresses and large hats are standing next to a large tree trunk .
[0.         0.         0.         ... 0.         0.08960153 0.        ]
A child swings on his stomach on a tire swing amidst trees .
A child swings on his stomach on a tire swing amidst trees .
[0.10861561 0.22771345 0.62031204 ... 0.         0.         0.        ]
men in suits and ties walking downsteps
men in suits and ties walking downsteps
[0. 0. 0. ... 0. 0. 0.]
A little girl jumps into the arms of her mother , standing in a pool .
A little girl jumps into the arms of her mother , standing in a pool .
[0.01384    0.         0.         ... 0.         0.         0.02119654]
Three girls are walking across a bridge covered with wood and surrounded by trees .
Three 

[0.23428118 0.         0.         ... 0.         0.46035287 0.        ]
A dog and a man wade into the lake .
A dog and a man wade into the lake .
[0.39112702 0.         0.22543791 ... 0.         0.         0.        ]
A large tent with a green cover at a campground .
A large tent with a green cover at a campground .
[0. 0. 0. ... 0. 0. 0.]
A large elderly woman in a green stripy dress is carrying shopping bags along a cobbled street .
A large elderly woman in a green stripy dress is carrying shopping bags along a cobbled street .
[0.         0.         0.         ... 0.         0.15509288 0.3755318 ]
The two children and the baby with the pink shirt are surrounded by toys .
The two children and the baby with the pink shirt are surrounded by toys .
[0.14786327 0.         0.         ... 0.         0.50640213 0.        ]
A small black dog is playing tug of war with a large brown dog wearing a yellow triangle .
A small black dog is playing tug of war with a large brown dog wearing a yellow

A brown dog is leaping over a fallen tree in the woods .
[0.         0.         0.07151387 ... 0.         0.18139035 0.        ]
Three little children in a grassy yard running towards the camera .
Three little children in a grassy yard running towards the camera .
[0.00221544 0.         0.         ... 0.         0.15142101 0.        ]
A man just caught a fish and it is fiesty !
A man just caught a fish and it is fiesty !
[0.10106885 0.         0.         ... 0.         0.15110417 0.        ]
A BMX biker attempts a trick off his dirt bike .
A BMX biker attempts a trick off his dirt bike .
[0.         0.         0.20793375 ... 0.         0.         0.        ]
A beige dog with a collar looks on as a brown dog swims in the water .
A beige dog with a collar looks on as a brown dog swims in the water .
[0.         0.         0.         ... 0.         0.18103622 0.        ]
A woman is sitting on a sidewalk with a cellphone at her ear .
A woman is sitting on a sidewalk with a cellphone at her

[0.         0.         0.         ... 0.         0.29798406 0.17018043]
A blond boy with a rubber innertube over his shoulder .
A blond boy with a rubber innertube over his shoulder .
[0.         0.         0.         ... 0.         0.12154585 0.0802061 ]
A brown and white dog is leaping over a log near water in the snow .
A brown and white dog is leaping over a log near water in the snow .
[0.03065178 0.         0.         ... 0.07287028 0.225107   0.        ]
A man in a purple jersey is falling down while chasing a player in a green jersey playing soccer
A man in a purple jersey is falling down while chasing a player in a green jersey playing soccer
[0.         0.         0.05723536 ... 0.         0.         0.        ]
A greyhound wearing a yellow jacket runs a race .
A greyhound wearing a yellow jacket runs a race .
[0.        0.        0.        ... 0.        0.6004739 0.       ]
A fat woman wearing faint blue top is blowing soap bubble .
A fat woman wearing faint blue top is blow

[0.         0.         0.26376033 ... 0.         0.         0.        ]
An older woman and a young girl standing in front of a large bush covered in pink flowers .
An older woman and a young girl standing in front of a large bush covered in pink flowers .
[0.         0.         0.         ... 0.         0.16815366 0.        ]
A little girl playing the guitar , some flowers to the left .
A little girl playing the guitar , some flowers to the left .
[0. 0. 0. ... 0. 0. 0.]
A group of musicians with instruments .
A group of musicians with instruments .
[0.         0.60820806 0.         ... 0.         0.         0.        ]
A soccer player kicking toward the ball with another player on the soaked ground .
A soccer player kicking toward the ball with another player on the soaked ground .
[0.         0.         0.         ... 0.         0.37361783 0.        ]
A man in a blue headband plays tennis .
A man in a blue headband plays tennis .
[0.         0.22144459 0.3962323  ... 0.         0.204

A young boy jumping into a lake .
[0.         0.         0.03476173 ... 0.         0.         0.05956659]
A broken down hummer gets towed on a truck bed .
A broken down hummer gets towed on a truck bed .
[0.05258192 0.         0.22130314 ... 0.         0.         0.        ]
A guy in black jacket eating .
A guy in black jacket eating .
[0. 0. 0. ... 0. 0. 0.]
A clown holding a broom with both arms raised .
A clown holding a broom with both arms raised .
[0. 0. 0. ... 0. 0. 0.]
A group of dressed-up people talking .
A group of dressed-up people talking .
[0.        0.        0.        ... 0.        0.2790333 0.       ]
a male reported in a black and white jacket interviewing a young woman
a male reported in a black and white jacket interviewing a young woman
[0.        0.        0.        ... 0.        0.2939927 0.662768 ]
A dark-haired , grey-suited man is leaning on a silver pole .
A dark-haired , grey-suited man is leaning on a silver pole .
[0. 0. 0. ... 0. 0. 0.]
A bicyclist rides 

A person climbing up a snowy mountain .
[0.         0.         0.         ... 0.         0.05431131 0.        ]
A woman is sitting near a flower bed overlooking a tunnel .
A woman is sitting near a flower bed overlooking a tunnel .
[0.         0.         0.         ... 0.         0.03195387 0.        ]
a young girl jumping out of the water at a pool
a young girl jumping out of the water at a pool
[0.10233045 0.         0.         ... 0.         0.         0.05086189]
A female snowboarder relaxing as the day comes to an end
A female snowboarder relaxing as the day comes to an end
[0.         0.         0.         ... 0.         0.20565869 0.28452548]
A girl is hula hooping on a sidewalk in New York .
A girl is hula hooping on a sidewalk in New York .
[0.42252642 0.15990776 0.         ... 0.         0.         0.        ]
A boy jumps into a not-so-crowded public pool .
A boy jumps into a not-so-crowded public pool .
[0.         0.04571231 0.         ... 0.         0.         0.        ]


A girl in jeans sitting on a white couch and smiling .
[0.         0.         0.         ... 0.         0.         0.01438082]
A little girl standing on a sandy hill on a beach .
A little girl standing on a sandy hill on a beach .
[0.         0.         0.         ... 0.         0.01303627 0.        ]
A boy in a green shirt and blue jeans riding a segway .
A boy in a green shirt and blue jeans riding a segway .
[0.         0.12950134 0.2128838  ... 0.         0.11073975 0.11747888]
A boy licks an older male 's face that 's covered in a blue and yellow creamy substance .
A boy licks an older male 's face that 's covered in a blue and yellow creamy substance .
[0.         0.         0.         ... 0.         0.         0.20031138]
A man and a woman kissing .
A man and a woman kissing .
[0. 0. 0. ... 0. 0. 0.]
A bald man in a blue polo shirt stands next to a brick building .
A bald man in a blue polo shirt stands next to a brick building .
[0.0389003  0.         0.02252007 ... 0.         

[0.04882579 0.         0.         ... 0.         0.48095888 0.0578783 ]
a group of young children playing in the grass with toilet paper
a group of young children playing in the grass with toilet paper
[0.         0.         0.         ... 0.         0.44798273 0.25991422]
a dog running on the beach
a dog running on the beach
[0.         0.25933957 0.         ... 0.         0.273244   0.        ]
a lone blue and white race car about to cross the finish line
a lone blue and white race car about to cross the finish line
[0.12924665 0.         0.         ... 0.         0.         0.        ]
A person in a scuba suit holds a very small lobster .
A person in a scuba suit holds a very small lobster .
[0.11849566 0.         0.         ... 0.         0.         0.        ]
A brown dog and a red dog frolicking on the waters edge on the beach .
A brown dog and a red dog frolicking on the waters edge on the beach .
[0. 0. 0. ... 0. 0. 0.]
A beige , white and black little dog is bounding towards t

[0. 0. 0. ... 0. 0. 0.]
A girl is hiding behind a painted wooden structure inside a building .
A girl is hiding behind a painted wooden structure inside a building .
[0.         0.         0.         ... 0.         0.34567612 0.        ]
Two girls clasp hands and pose for a picture .
Two girls clasp hands and pose for a picture .
[0.         0.         0.         ... 0.         0.19667439 0.20310691]
A dog attacking a guy .
A dog attacking a guy .
[0.         0.         0.         ... 0.         0.09248218 0.        ]
A flock of birds flying over a shoreline .
A flock of birds flying over a shoreline .
[0.         0.5168836  0.         ... 0.         0.07672964 0.        ]
A man is sitting on a bench behind a bike .
A man is sitting on a bench behind a bike .
[0.13668725 0.         0.         ... 0.         0.         0.        ]
a boy rides his ripstik on the street .
a boy rides his ripstik on the street .
[0.         0.         0.19809677 ... 0.         0.60241723 0.01591222]
A dog 

[0.         0.         0.07215437 ... 0.         0.         0.        ]
A barefoot man in his pajamas is looking toward the sky while walking on the tennis court .
A barefoot man in his pajamas is looking toward the sky while walking on the tennis court .
[0.         0.         0.21145657 ... 0.         0.         0.        ]
A girl on the phone standing in front of beautiful plants is passed by another smiling girl .
A girl on the phone standing in front of beautiful plants is passed by another smiling girl .
[0.         0.0905633  0.         ... 0.         0.1253782  0.38603026]
A boy with glasses is standing on top of a rocky peak with hands in his pockets .
A boy with glasses is standing on top of a rocky peak with hands in his pockets .
[0.         0.         0.         ... 0.         0.16136879 0.00463743]
a bicyclist wearing a helmet jumping a trick on his back tire
a bicyclist wearing a helmet jumping a trick on his back tire
[0.         0.         0.07256078 ... 0.         0.0

In [141]:
input_words = sorted(list(input_words ))
target_words  = sorted(list(target_words ))
num_encoder_tokens = len(input_words)
num_decoder_tokens = len(target_words)
max_encoder_seq_length = max([len(txt) for txt in input_texts])+2
max_decoder_seq_length = max([len(txt) for txt in target_texts])

print('Number of samples:', len(input_texts))
print('Number of unique input tokens:', num_encoder_tokens)
print('Number of unique output tokens:', num_decoder_tokens)
print('Max sequence length for inputs:', max_encoder_seq_length)
print('Max sequence length for outputs:', max_decoder_seq_length)

Number of samples: 500
Number of unique input tokens: 1063
Number of unique output tokens: 1063
Max sequence length for inputs: 33
Max sequence length for outputs: 33


In [142]:
input_token_index = dict(
    [(char, i) for i, char in enumerate(input_words )])
target_token_index = dict(
    [(char, i) for i, char in enumerate(target_words )])
print(input_token_index)
print(target_token_index)

{u'all': 63, u'motocross': 604, u'seated': 782, u'pointing': 702, u'hands': 458, u'yellow': 1060, u'four': 416, u'kicks': 528, u'protest': 716, u'skate': 822, u'Olympics': 38, u'ice': 501, u'hanging': 459, u'go': 432, u'follow': 407, u'chair': 222, u'disk': 311, u'displaying': 313, u'children': 233, u'Brown': 17, u'somthing': 856, u'puddle': 718, u'fenced': 378, u'young': 1061, u'riverbank': 755, u'to': 956, u'bicycler': 145, u'helps': 473, u'under': 991, u'jumped': 522, u'fences': 379, u'hats': 464, u'playground': 697, u'brown': 180, u'woman': 1047, u'outside': 650, u'far': 371, u'tent': 938, u'baton': 128, u'helmet': 472, u'closeup': 248, u'artwork': 87, u'mixing': 602, u'word': 1054, u'bubbles': 183, u'fireplace': 387, u'leads': 549, u'school': 777, u'dark-haired': 296, u'wooden': 1052, u'turns': 986, u'sticks': 882, u'trots': 979, u'laying': 547, u'bright': 179, u'bikers': 151, u'this': 944, u'sand': 773, u'race': 729, u'launches': 546, u'small': 841, u'guy': 449, u'woven': 1056, u

In [0]:
encoder_input_data = np.zeros(
    (len(input_texts), max_encoder_seq_length, num_encoder_tokens),
    dtype='float32')
decoder_input_data = np.zeros(
    (len(input_texts), max_decoder_seq_length, num_decoder_tokens),
    dtype='float32')
decoder_target_data = np.zeros(
    (len(input_texts), max_decoder_seq_length, num_decoder_tokens),
    dtype='float32')
img_tar_data=np.zeros(
    (len(input_texts), 4096),
    dtype='float32')

In [144]:
for i, (input_text, target_text) in enumerate(zip(input_texts, target_texts)):
    for t, char in enumerate(input_text):
        encoder_input_data[i, t, input_token_index[char]] = 1.
    img_tar_data[i]=img_mat[i]    
    for t, char in enumerate(target_text):
        # decoder_target_data is ahead of decoder_input_data by one timestep
        decoder_input_data[i, t, target_token_index[char]] = 1.
        if t > 0:
            # decoder_target_data will be ahead by one timestep
            # and will not include the start character.
            decoder_target_data[i, t - 1, target_token_index[char]] = 1.
print(encoder_input_data.shape)

(500, 33, 1063)


In [0]:
from keras import backend as K
from keras.layers import Input, Lambda
from keras.layers import Concatenate, Dense, LSTM, Input, concatenate

def crop1(dimension, start, end):
    # Crops (or slices) a Tensor on a given dimension from start to end
    # example : to crop tensor x[:, :, 5:10]
    # call slice(2, 5, 10) as you want to crop on the second dimension
    def func(x):
        if dimension == 0:
            return x[start: end,:]
        if dimension == 1:
            return x[:, start: end]
        if dimension == 2:
            return x[:, :, start: end]
        if dimension == 3:
            return x[:, :, :, start: end]
        if dimension == 4:
            return x[:, :, :, :, start: end]
    return Lambda(func,name='layer71')


def crop2(dimension, start, end):
    # Crops (or slices) a Tensor on a given dimension from start to end
    # example : to crop tensor x[:, :, 5:10]
    # call slice(2, 5, 10) as you want to crop on the second dimension
    def func(x):
        if dimension == 0:
            return x[start: end,:]
        if dimension == 1:
            return x[:, start: end]
        if dimension == 2:
            return x[:, :, start: end]
        if dimension == 3:
            return x[:, :, :, start: end]
        if dimension == 4:
            return x[:, :, :, :, start: end]
    return Lambda(func,name='layer72')

#Lambda(x[1,:,:],name='layer7')

In [0]:
#@title
from keras import backend as K
from keras.layers import Input, Lambda
from keras.layers import Concatenate, Dense, LSTM, Input, concatenate
from keras import losses
# Define an input sequence and process it.
encoder_inputs = Input(shape=(None, num_encoder_tokens),name='layer0')
encoder = LSTM(latent_dim, return_state=True,name='layer3')
encoder_outputs, state_h, state_c = encoder(encoder_inputs)
# We discard `encoder_outputs` and only keep the states.
concated_state = concatenate(([state_h, state_c]),axis=1,name='layer4')


inter_mediate_state = Dense(4096,name='layer5')(concated_state)


compressed_state=Dense(1024,name="layer6")(inter_mediate_state)
t1=crop1(1,0,512)(compressed_state)
t2=crop2(1,512,1024)(compressed_state)

encoder_states = [t1,t2]
#encoder_states = [state_h, state_c]

decoder_inputs = Input(shape=(None, num_decoder_tokens))
# We set up our decoder to return full output sequences,
# and to return internal states as well. We don't use the
# return states in the training model, but we will use them in inference.
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)
decoder_dense = Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

def custom_loss(y_true, y_pred):
    loss2=losses.categorical_crossentropy(y_true, y_pred)
    return loss2

# Define the model that will turn
# `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
model = Model([encoder_inputs, decoder_inputs],[inter_mediate_state,decoder_outputs])
#[inter_mediate_state,
# Run training
#[img_tar_data,
model.compile(optimizer='adam', loss=custom_loss, metrics=['accuracy'])
model.fit([encoder_input_data, decoder_input_data],[img_tar_data, decoder_target_data],
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2)
# Save model
model.save('s2sss.h5')

In [0]:
#@title
from keras import backend as K
from keras.layers import Input, Lambda
from keras.layers import Concatenate, Dense, LSTM, Input, concatenate
from keras import losses
# Define an input sequence and process it.
encoder_inputs = Input(shape=(None, num_encoder_tokens),name='layer0')
encoder = LSTM(latent_dim, return_state=True,name='layer3')
encoder_outputs, state_h, state_c = encoder(encoder_inputs)
# We discard `encoder_outputs` and only keep the states.
concated_state = concatenate(([state_h, state_c]),axis=1,name='layer4')


inter_mediate_state = Dense(4096,name='layer5')(concated_state)


compressed_state=Dense(1024,name="layer6")(inter_mediate_state)
t1=crop1(1,0,512)(compressed_state)
t2=crop2(1,512,1024)(compressed_state)

encoder_states = [t1,t2]
#encoder_states = [state_h, state_c]

# Set up the decoder, using `encoder_states` as initial state.
decoder_inputs = Input(shape=(None, num_decoder_tokens))
# We set up our decoder to return full output sequences,
# and to return internal states as well. We don't use the
# return states in the training model, but we will use them in inference.
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)
decoder_dense = Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

def custom_loss(y_true, y_pred):
    loss1=losses.mean_squared_error(y_true[0],y_pred[0])
    loss2=losses.binary_crossentropy(y_true[1], y_pred[1])
    return K.mean(loss1*10+loss2)

# Define the model that will turn
# `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
model = Model([encoder_inputs, decoder_inputs],[inter_mediate_state,decoder_outputs])

# Run training
model.compile(optimizer='adam', loss=custom_loss)
model.fit([encoder_input_data, decoder_input_data],[img_tar_data, decoder_target_data],
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2)
# Save model
model.save('s2s.h5')

In [146]:
from keras import backend as K
from keras.layers import Input, Lambda
from keras.layers import Concatenate, Dense, LSTM, Input, concatenate
from keras import losses
#from keras import metrics

# Define an input sequence and process it.
encoder_inputs = Input(shape=(None, num_encoder_tokens),name='layer0')
img_inp_st = Input(shape=(4096,),name='layer00')
encoder = LSTM(latent_dim, return_state=True,name='layer3')
encoder_outputs, state_h, state_c = encoder(encoder_inputs)
# We discard `encoder_outputs` and only keep the states.
concated_state = concatenate(([state_h, state_c]),axis=1,name='layer4')


inter_mediate_state = Dense(4096,name='layer5')(concated_state)


compressed_state=Dense(1024,name="layer6")(inter_mediate_state)
t1=crop1(1,0,512)(compressed_state)
t2=crop2(1,512,1024)(compressed_state)

encoder_states = [t1,t2]
#encoder_states = [state_h, state_c]

# Set up the decoder, using `encoder_states` as initial state.
decoder_inputs = Input(shape=(None, num_decoder_tokens))
# We set up our decoder to return full output sequences,
# and to return internal states as well. We don't use the
# return states in the training model, but we will use them in inference.
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)
decoder_dense = Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)


# Define the model that will turn
# `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
model = Model([encoder_inputs, decoder_inputs,img_inp_st],[decoder_outputs,inter_mediate_state])
xent_loss =  K.sum(losses.binary_crossentropy(encoder_inputs, decoder_outputs))
vae_loss = xent_loss

model.add_loss(vae_loss)
model.compile(optimizer='rmsprop')
#[inter_mediate_state,
# Run training
#[img_tar_data,
#model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit([encoder_input_data, decoder_input_data,img_tar_data],shuffle=True,
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2)
# Save model
model.save('s2s.h5')

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:46: UserWarning: Output "dense_19" missing from loss dictionary. We assume this was done on purpose, and we will not be expecting any data to be passed to "dense_19" during training.
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:46: UserWarning: Output "layer5" missing from loss dictionary. We assume this was done on purpose, and we will not be expecting any data to be passed to "layer5" during training.


Train on 400 samples, validate on 100 samples
Epoch 1/200
400/400 [==============================] - 6s 14ms/step - loss: 25.0559 - val_loss: 11.8814
Epoch 2/200
400/400 [==============================] - 1s 3ms/step - loss: 11.5691 - val_loss: 11.2394
Epoch 3/200
400/400 [==============================] - 1s 3ms/step - loss: 10.9380 - val_loss: 11.0343
Epoch 4/200
400/400 [==============================] - 1s 3ms/step - loss: 10.6766 - val_loss: 10.8549
Epoch 5/200
400/400 [==============================] - 1s 3ms/step - loss: 10.4802 - val_loss: 10.7651
Epoch 6/200
400/400 [==============================] - 1s 3ms/step - loss: 10.3685 - val_loss: 10.7762
Epoch 7/200
400/400 [==============================] - 1s 3ms/step - loss: 10.2887 - val_loss: 10.8325
Epoch 8/200
400/400 [==============================] - 1s 3ms/step - loss: 10.2789 - val_loss: 10.8054
Epoch 9/200
400/400 [==============================] - 1s 3ms/step - loss: 10.2066 - val_loss: 10.8270
Epoch 10/200
400/400 [====

200/400 [==============>...............] - ETA: 0s - loss: 6.3395400/400 [==============================] - 1s 3ms/step - loss: 6.3587 - val_loss: 10.5237
Epoch 97/200
400/400 [==============================] - 1s 3ms/step - loss: 6.2935 - val_loss: 10.5485
Epoch 98/200
400/400 [==============================] - 1s 3ms/step - loss: 6.3803 - val_loss: 10.5764
Epoch 99/200
400/400 [==============================] - 1s 3ms/step - loss: 6.2813 - val_loss: 10.6852
Epoch 100/200
400/400 [==============================] - 1s 3ms/step - loss: 6.2155 - val_loss: 10.6433
Epoch 101/200
400/400 [==============================] - 1s 3ms/step - loss: 6.2161 - val_loss: 10.5981
Epoch 102/200
400/400 [==============================] - 1s 3ms/step - loss: 6.0421 - val_loss: 10.5364
Epoch 103/200
400/400 [==============================] - 1s 3ms/step - loss: 6.0827 - val_loss: 10.7794
Epoch 104/200
400/400 [==============================] - 1s 3ms/step - loss: 5.9928 - val_loss: 10.6607
Epoch 105/200
40

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py:2368: UserWarning: Layer lstm_19 was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'layer71_18/strided_slice:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'layer72_18/strided_slice:0' shape=(?, 512) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  str(node.arguments) + '. They will not be included '


In [0]:
encoder_model = Model(encoder_inputs, encoder_states)

decoder_state_input_h = Input(shape=(latent_dim,))
decoder_state_input_c = Input(shape=(latent_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_inputs, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)


# Reverse-lookup token index to decode sequences back to
# something readable.
reverse_input_char_index = dict(
    (i, char) for char, i in input_token_index.items())
reverse_target_char_index = dict(
    (i, char) for char, i in target_token_index.items())

In [0]:
model.summary()

In [0]:
lat1ent_dim=512
def decode_sequence(input_seq,ind):
    # Encode the input as state vectors.
    #input_seq
    #isis = K.variable(value=input_seq)
    #tmp=K.ran()
    #img_tar_data[ind:ind+1]=img_tar_data[ind:ind+1]-img_tar_data[ind+1:ind+2]+1
    #print(img_tar_data[ind:ind+1])
    #print (img_tar_data)
    get_3rd_layer_output = K.function([model.get_layer(name='layer6').input],
                                       [model.get_layer(name='layer71').output])
    layer3_output_t1 = get_3rd_layer_output([img_tar_data[ind:ind+1]])[0]
    get_3rd_layer_output = K.function([model.get_layer(name='layer6').input],
                                      [model.get_layer(name='layer72').output])
    layer3_output_t2 = get_3rd_layer_output([img_tar_data[ind:ind+1]])[0]
    states_value=[layer3_output_t1,layer3_output_t2]
    #states_value=encoder_model.predict(input_seq)
    #print(states_value_d[0])
    #print(states_value[0])
   
      
    target_seq = np.zeros((1, 1, num_decoder_tokens))
    # Populate the first character of target sequence with the start character.
    target_seq[0, 0, target_token_index['STR']] = 1.

    # Sampling loop for a batch of sequences
    # (to simplify, here we assume a batch of size 1).
    stop_condition = False
    decoded_sentence = ''
    while not stop_condition:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value)

        # Sample a token
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_char = reverse_target_char_index[sampled_token_index]
        decoded_sentence += sampled_char+' '

        # Exit condition: either hit max length
        # or find stop character.
        if (sampled_char == 'EOS' or
           len(decoded_sentence) > 60):
            stop_condition = True

        # Update the target sequence (of length 1).
        target_seq = np.zeros((1, 1, num_decoder_tokens))
        target_seq[0, 0, sampled_token_index] = 1.

        # Update states
        states_value = [h, c]

    return decoded_sentence


In [154]:

for seq_index in range(100):
    
    # Take one sequence (part of the training set)
    # for trying out decoding.
    #seq_index=10
    
    input_seq = encoder_input_data[seq_index: seq_index + 1]
    decoded_sentence = decode_sequence(input_seq,seq_index)
    print('-')
    print('Input sentence:', input_texts[seq_index])
    print('Decoded sentence:', decoded_sentence)

-
Input sentence: [u'A', u'black', u'dog', u'is', u'running', u'after', u'a', u'white', u'dog', u'in', u'the', u'snow', u'.']
Decoded sentence: A big black dog bares its teeth while running through the snow 
-
Input sentence: [u'A', u'little', u'baby', u'plays', u'croquet', u'.']
Decoded sentence: A boy jumps through the air onto something red . wheelie pose 
-
Input sentence: [u'A', u'brown', u'dog', u'in', u'the', u'snow', u'has', u'something', u'hot', u'pink', u'in', u'its', u'mouth', u'.']
Decoded sentence: A brown dog in the snow has something hot pink in its mouth . 
-
Input sentence: [u'A', u'brown', u'dog', u'is', u'running', u'along', u'a', u'beach', u'.']
Decoded sentence: A brown dog is running along a beach . younger roll in skirt 
-
Input sentence: [u'A', u'black', u'and', u'white', u'dog', u'with', u'a', u'red', u'Frisbee', u'standing', u'on', u'a', u'sandy', u'beach', u'.']
Decoded sentence: A black dog running with a stuffed bird in its mouth and another 
-
Input senten

-
Input sentence: [u'A', u'brown', u'dog', u'is', u'standing', u'in', u'a', u'lake', u'.']
Decoded sentence: A brown dog playing with bubbles . colorful on the beach . fetch 
-
Input sentence: [u'A', u'dog', u'plays', u'with', u'a', u'toy', u'in', u'the', u'grass', u'.']
Decoded sentence: A brown dog bares its fangs . logo running through the snow . 
-
Input sentence: [u'A', u'elderly', u'man', u'in', u'a', u'straw', u'hat', u'is', u'sitting', u'on', u'a', u'bench', u'.']
Decoded sentence: A elderly man in a straw hat is sitting on a bench . Olympics 
-
Input sentence: [u'A', u'dark-haired', u'man', u'in', u'a', u'red', u't-shirt', u',', u'with', u'a', u'beard', u',', u'playing', u'the', u'guitar', u'in', u'a', u'park', u'.']
Decoded sentence: A child in a grey jacket is running along a leafy path . get 
-
Input sentence: [u'Two', u'black', u'dogs', u'are', u'jumping', u'and', u'playing', u'with', u'a', u'yellow', u'tennis', u'ball', u'in', u'the', u'snow', u'.']
Decoded sentence: A do

In [230]:

for seq_index in range(25):
    
    # Take one sequence (part of the training set)
    # for trying out decoding.
    
    input_seq = encoder_input_data[seq_index: seq_index + 1]
    decoded_sentence = decode_sequence(input_seq,seq_index)
    print('-')
    print('Input sentence:', input_texts[seq_index])
    print('Decoded sentence:', decoded_sentence)

-
Input sentence: [u'A', u'black', u'dog', u'is', u'running', u'after', u'a', u'white', u'dog', u'in', u'the', u'snow', u'.']
Decoded sentence: A brown dog is carrying a wet stick on the shore of the ocean 
-
Input sentence: [u'A', u'little', u'baby', u'plays', u'croquet', u'.']
Decoded sentence: A brown dog in the snow has something hot pink in its mouth . 
-
Input sentence: [u'A', u'brown', u'dog', u'in', u'the', u'snow', u'has', u'something', u'hot', u'pink', u'in', u'its', u'mouth', u'.']
Decoded sentence: A brown dog is carrying a wet stick on the shore of the ocean 
-
Input sentence: [u'A', u'brown', u'dog', u'is', u'running', u'along', u'a', u'beach', u'.']
Decoded sentence: A brown dog is carrying a wet stick on the shore of the ocean 
-
Input sentence: [u'A', u'black', u'and', u'white', u'dog', u'with', u'a', u'red', u'Frisbee', u'standing', u'on', u'a', u'sandy', u'beach', u'.']
Decoded sentence: A brown dog in the snow has something hot pink in its mouth . 
-
Input sentence: